name: Typecheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: cd cloud-functions && npm ci

      - name: Run Typecheck
        run: cd cloud-functions && npx tsc --noEmit
